#pragma once

enum CollisionLayer
{
	COLLISION_LAYER_NONE = 0
	, COLLISION_LAYER_STATIC = 1 << 0
	, COLLISION_LAYER_DYNAMIC = 1 << 1
	, COLLISION_LAYER_KINEMATIC = 1 << 2
	, COLLISION_LAYER_CUSTOM_0 = 1 << 3
	, COLLISION_LAYER_CUSTOM_1 = 1 << 4
	, COLLISION_LAYER_CUSTOM_2 = 1 << 5
	, COLLISION_LAYER_CUSTOM_3 = 1 << 6
	, COLLISION_LAYER_CUSTOM_5 = 1 << 7
	, COLLISION_LAYER_CUSTOM_6 = 1 << 8
	, COLLISION_LAYER_CUSTOM_7 = 1 << 9
	, COLLISION_LAYER_CUSTOM_8 = 1 << 10
	, COLLISION_LAYER_CUSTOM_9 = 1 << 11
	, COLLISION_LAYER_CUSTOM_10 = 1 << 12
	, COLLISION_LAYER_CUSTOM_11 = 1 << 13
	, COLLISION_LAYER_CUSTOM_12 = 1 << 14
};