#pragma once

enum ChannelGroupType
{
	CHANNEL_GROUP_MUSIC = 0
	, CHANNEL_GROUP_EFFECT = 1
	, CHANNEL_GROUP_VOICE = 2
	, CHANNEL_GROUP_CUSTOM_0 = 3
	, CHANNEL_GROUP_CUSTOM_1 = 4
	, CHANNEL_GROUP_CUSTOM_2 = 5
	, CHANNEL_GROUP_CUSTOM_3 = 6
	, CHANNEL_GROUP_CUSTOM_4 = 7
	, CHANNEL_GROUP_CUSTOM_5 = 8
	, CHANNEL_GROUP_CUSTOM_6 = 9
};