#pragma once

#include "SerializationMacros.hpp"
#include <glm/fwd.hpp>

SERIALIZATION_ARCHIVE_FORWARD_DECLARATION()


SERIALIZATION_SAVE_DECLARATION(glm::vec2);
SERIALIZATION_SAVE_DECLARATION(glm::uvec2);
SERIALIZATION_SAVE_DECLARATION(glm::vec3);
SERIALIZATION_SAVE_DECLARATION(glm::uvec3);
SERIALIZATION_SAVE_DECLARATION(glm::vec4);
SERIALIZATION_SAVE_DECLARATION(glm::uvec4);

SERIALIZATION_LOAD_DECLARATION(glm::vec2);
SERIALIZATION_LOAD_DECLARATION(glm::uvec2);
SERIALIZATION_LOAD_DECLARATION(glm::vec3);
SERIALIZATION_LOAD_DECLARATION(glm::uvec3);
SERIALIZATION_LOAD_DECLARATION(glm::vec4);
SERIALIZATION_LOAD_DECLARATION(glm::uvec4);