echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\nvToolsExt64_1.dll" "Binaries\x64\Release\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\nvToolsExt64_1.dll" "Binaries\x64\Release\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysXDevice64.dll" "Binaries\x64\Release\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysXDevice64.dll" "Binaries\x64\Release\"

echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3_x64.dll" "Binaries\x64\Release\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3_x64.dll" "Binaries\x64\Release\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CharacterKinematic_x64.dll" "Binaries\x64\Release\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CharacterKinematic_x64.dll" "Binaries\x64\Release\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3Common_x64.dll" "Binaries\x64\Release\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3Common_x64.dll" "Binaries\x64\Release\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3Cooking_x64.dll" "Binaries\x64\Release\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3Cooking_x64.dll" "Binaries\x64\Release\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3Gpu_x64.dll" "Binaries\x64\Release\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3Gpu_x64.dll" "Binaries\x64\Release\"

echo xcopy /E /I /Y "Binaries\x64\Release\*.dll" "..\..\..\x64\Release\"
xcopy /E /I /Y "Binaries\x64\Release\*.dll" "..\..\..\x64\Release\"
