echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\nvToolsExt64_1.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\nvToolsExt64_1.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysXDevice64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysXDevice64.dll" "Binaries\x64\Debug\"

echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3DEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3DEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CharacterKinematicDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CharacterKinematicDEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CommonDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CommonDEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CookingDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3CookingDEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3GpuDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\PhysXSDK\Bin\vc12win64\PhysX3GpuDEBUG_x64.dll" "Binaries\x64\Debug\"

echo xcopy /E /I /Y "Binaries\x64\Debug\*.dll" "..\..\..\x64\Debug\"
xcopy /E /I /Y "Binaries\x64\Debug\*.dll" "..\..\..\x64\Debug\"
