echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\nvToolsExt64_1.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\nvToolsExt64_1.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysXDevice64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysXDevice64.dll" "Binaries\x64\Debug\"

echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3DEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3DEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3CharacterKinematicDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3CharacterKinematicDEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3CommonDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3CommonDEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3CookingDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3CookingDEBUG_x64.dll" "Binaries\x64\Debug\"
echo xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3GpuDEBUG_x64.dll" "Binaries\x64\Debug\"
xcopy /E /I /Y "..\..\..\Vendors\PhysX\Bin\PhysX3GpuDEBUG_x64.dll" "Binaries\x64\Debug\"

echo xcopy /E /I /Y "Binaries\x64\Debug\*.dll" "..\..\..\x64\Debug\"
xcopy /E /I /Y "Binaries\x64\Debug\*.dll" "..\..\..\x64\Debug\"
